[project]
name = "ai-agent-benchmarking"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Joseph Bolton", email = "joseph.jazz.bolton@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
